name: Continuous Integration with Github Actions

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Build Application JAR
      working-directory: ./ProjetosSpring/api-client
      run: mvn clean package

    - name: Docker Compose Build
      working-directory: ./ProjetosSpring
      run: docker compose build

    - name: Push to Docker Hub Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/api-client:latest ${{ secrets.DOCKER_USERNAME }}/api-client:${{ github.run_id }}

        docker push ${{ secrets.DOCKER_USERNAME }}/api-client:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/api-client:latest
