name: Continuos Integration with GitHub Actions

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
        
    - name: Build Application Jar
      working-directory: ./ProjetosSpring/api-client
      run: mvn clean package
      
    - name: Docker Composer Build
      working-directory: ./ProjetosSpring
      run: docker compose build
      
    - name: Push to Docker Hub Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/api-client:latest ${{ secrets.DOCKER_USERNAME }}/api-client:${{ github.run_id }} 
        docker push ${{ secrets.DOCKER_USERNAME }}/api-client:${{ github.run_id }}

    
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
